export enum SSE {
    IDLE  = "SSE_CONNECTION_ESTABLISHED",
    CONNECTION_ESTABLISHED = "SSE_CONNECTION_ERROR",
    CONNECTION_ERROR = "SSE_CONNECTION_ERROR",
    CONNECTION_CLOSED = "SSE_CONNECTION_CLOSED"
}